# Autogenerated wrapper script for FastME_jll for aarch64-apple-darwin
export fastme, fastmeMP

using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("FastME")
JLLWrappers.@declare_executable_product(fastme)
JLLWrappers.@declare_executable_product(fastmeMP)
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll)
    JLLWrappers.@init_executable_product(
        fastme,
        "bin/fastme",
    )

    JLLWrappers.@init_executable_product(
        fastmeMP,
        "bin/fastmeMP",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
