# Autogenerated wrapper script for FastME_jll for i686-w64-mingw32
export fastme, fastmeMP

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("FastME")
JLLWrappers.@declare_executable_product(fastme)
JLLWrappers.@declare_executable_product(fastmeMP)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        fastme,
        "bin\\fastme.exe",
    )

    JLLWrappers.@init_executable_product(
        fastmeMP,
        "bin\\fastmeMP.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
